# coding: utf-8

# flake8: noqa

"""
    OpenLigaDB-API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from openligadb.api.matchdata_api import MatchdataApi
# import ApiClient
from openligadb.api_client import ApiClient
from openligadb.configuration import Configuration
# import models into sdk package
from openligadb.models.bl_table_team import BlTableTeam
from openligadb.models.global_result_info import GlobalResultInfo
from openligadb.models.goal import Goal
from openligadb.models.goal_getter import GoalGetter
from openligadb.models.group import Group
from openligadb.models.league import League
from openligadb.models.location import Location
from openligadb.models.match import Match
from openligadb.models.match_result import MatchResult
from openligadb.models.result_info import ResultInfo
from openligadb.models.sport import Sport
from openligadb.models.team import Team
